mindmap
  root((Product))
    Server
      Services
        auth Service
        store Service
        compute Service
            Queued tasks
            In Place tasks
      Dockers
        radis
        mqtt
        qdrant
      Packages
        media tools
        ml tools

    Clients
      Python
        Standard Client library
            supports all Services
        Use case demo 
      Dart
        Standard Client library
            supports all Services
        Use case demo 
